### ISSUE TITLE
Add Entrust nShield information

### ISSUE THREAD

**Issue by primetomas** [pkic/remote-key-attestation#3]
Add information about Entrust nChield to the table

**Comment by pacet90** [comment]
The Entrust nShield HSMs do not currently support (remote) key attestation resulting in a cryptographically verifiable attestation.
 
Users with direct access to the HSM can attest the origin of a key and prove that it was generated within an Entrust nShield HSM and ensure that the key attributes have not been changed since creation but this does not result in a cryptographically verifiable attestation.
 
Remote Key Attestation is on our roadmap and we will keep this page and the PKI Consortium updated on any developments.

**Comment by mihkeltammsalu** [comment]
If available, where I could find the nShield roadmap or retrieve info about HSM key attestation progress?

**Comment by vanbroup** [comment]
@pacet90 Giuseppe, any updates we can incoporate about remote key attestation support?

**Comment by mihkeltammsalu** [comment]
Any news?

**Comment by othouvou** [comment]
I am seeing that Entrust now offers [key attestation](https://nshielddocs.entrust.com/key-attestation-docs/v1.0.2/intro.html) 

My 2c: through the verification, it should be visible whether:
- the key is exportable
- the exact FIPS level of the HSM device the key resides, for compliance reasons with AATL and CAB/F CSWG
